# Generated by Django 2.0.6 on 2019-06-22 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='State_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='data_month')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('median_one_bed', models.IntegerField(null=True)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.State')),
            ],
        ),
    ]
