# Generated by Django 2.0.6 on 2019-06-22 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_state_data_median_two_bed'),
    ]

    operations = [
        migrations.AddField(
            model_name='state_data',
            name='median_four_bed',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='state_data',
            name='median_sfr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='state_data',
            name='median_studio',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='state_data',
            name='median_three_bed',
            field=models.IntegerField(null=True),
        ),
    ]
