# Generated by Django 2.0.6 on 2019-06-22 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0004_auto_20190622_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='County_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='data_month')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('median_studio', models.IntegerField(null=True)),
                ('median_one_bed', models.IntegerField(null=True)),
                ('median_two_bed', models.IntegerField(null=True)),
                ('median_three_bed', models.IntegerField(null=True)),
                ('median_four_bed', models.IntegerField(null=True)),
                ('median_sfr', models.IntegerField(null=True)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.County')),
            ],
        ),
        migrations.RenameField(
            model_name='state',
            old_name='county',
            new_name='country',
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.State'),
        ),
    ]
