# Generated by Django 2.0.6 on 2019-06-23 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0006_state_map_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('county', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rentals.County')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.State')),
            ],
        ),
    ]
