# Generated by Django 2.0.6 on 2019-06-25 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0007_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='data_month')),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('median_studio', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_one_bed', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_two_bed', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_three_bed', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_four_bed', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_sfr', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_sqft_studio', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('median_sqft_one_bed', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('median_sqft_two_bed', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('median_sqft_three_bed', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('median_sqft_four_bed', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('median_sqft_sfr', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('median_list_price_all', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_list_price_bot', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_list_price_top', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('sales_count', models.IntegerField(null=True)),
                ('foreclosure_resale_perc', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('median_daily_listings_all', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('monthly_listings_all', models.IntegerField(null=True)),
                ('sales_list_ratio', models.DecimalField(decimal_places=10, max_digits=12, null=True)),
                ('days_on_zillow', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_price_reduced_all', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('price_cut_seas_adj_all', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('median_sqft_list_price_all', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('median_sqft_list_price_bot', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('median_sqft_list_price_top', models.DecimalField(decimal_places=4, max_digits=12, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentals.City')),
            ],
        ),
        migrations.AlterField(
            model_name='county_data',
            name='median_four_bed',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='county_data',
            name='median_one_bed',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='county_data',
            name='median_sfr',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='county_data',
            name='median_studio',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='county_data',
            name='median_three_bed',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='county_data',
            name='median_two_bed',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='state_data',
            name='median_four_bed',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='state_data',
            name='median_one_bed',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='state_data',
            name='median_sfr',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='state_data',
            name='median_studio',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='state_data',
            name='median_three_bed',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='state_data',
            name='median_two_bed',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
