# Generated by Django 2.0.6 on 2019-06-27 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0008_auto_20190625_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='lat',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='lon',
            field=models.DecimalField(decimal_places=4, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population_density',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='population_proper',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
